<?php
/*
Plugin Name: Slug for attached posts by image galleries
Plugin URI: http://www.pascualyco.com/Slug4apig.tgz
Description: The Slug4apig plugin allows WordPress users to edit the SEO friendly URL (aka slug) for the autogenerated attachment
posts created by the built WordPress gallery.
Author: Claudio Pascual
Version: 1.0
Author URI: http://www.pascualyco.com/
License: GPL2

Copyright 2011 Claudio Pascual Cruz (email : clapas@pascualyco.com)

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License, version 2, as 
published by the Free Software Foundation.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/

function rt_image_attachment_fields_to_edit($form_fields, $post) {
        $form_fields["post-name"] = array(
        "label" => __("Post name"),
        "input" => "text", // default
        "value" => $post->post_name,
                //"helps" => __("To be used with special slider added via [rt_carousel] shortcode."),
    );
   return $form_fields;
}
add_filter("attachment_fields_to_edit", "rt_image_attachment_fields_to_edit", null, 2);

function rt_image_attachment_fields_to_save($post, $attachment) {
    // $attachment part of the form $_POST ($_POST[attachments][postID])
        // $post['post_type'] == 'attachment'
    if( isset($attachment['post-name']) ){
        // update_post_meta(postID, meta_key, meta_value);
        //$post->post_name= $attachment['post-name'];
        $post['post_name']= $attachment['post-name'];
    }
    return $post;
}
add_filter("attachment_fields_to_save", "rt_image_attachment_fields_to_save", null , 2);

?>
